name = "ti2_html"
version = "1.0.0"

[dependencies]
vxml = { "path" = "../../vistuleB/wly/vxml" }
writerly = { "path" = "../../vistuleB/wly/writerly" }
desugaring = { "path" = "../../vistuleB/wly/desugaring" }

argv = ">= 1.0.2 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.3.0 and < 3.0.0"
gleam_time = ">= 1.3.0 and < 2.0.0"
on = ">= 1.0.1 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
