name = "ti2_html"
version = "1.0.0"

[dependencies]
blamedlines = { "path" = "../../vistuleB/blamedlines" }
vxml_parser = { "path" = "../../vistuleB/vxml_parser" }
writerly_parser = { "path" = "../../vistuleB/writerly_parser" }
lbp_desugaring = { "path" = "../lbp_desugaring" }

argv = ">= 1.0.2 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
