name = "ti2_html"
version = "1.0.0"

[dependencies]
blamedlines = { git = "git@github.com:vistuleB/blamedlines", ref = "583ddcf" }
lbp_desugaring = { git = "git@github.com:MrChaker/lbp_desugaring", ref = "3daca38" }
vxml_parser = { git = "git@github.com:vistuleB/vxml_parser", ref = "7ef7d21" }
writerly_parser = { git = "git@github.com:vistuleB/writerly_parser", ref = "67cf25e" }

argv = ">= 1.0.2 and < 2.0.0"
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
shellout = ">= 1.6.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
